import {mkdirSync} from 'node:fs';
mkdirSync('test-results',{recursive:true});
import { chromium } from '@playwright/test';
const browser=await chromium.launch({headless:true,channel:"chrome"});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://localhost:5173');await page.getByRole('button',{name:'Enter portfolio'}).click();await page.locator('main').waitFor();
await page.waitForTimeout(1500);
await page.screenshot({path:'test-results/desktop-preview.png',fullPage:true});
await page.getByRole('button',{name:'Web development',exact:true}).click();
if(await page.locator('.project-card').count()!==3)throw new Error('Filter failed');
await page.getByRole('button',{name:'View CureApp project'}).click();
await page.getByRole('dialog').waitFor();
const animation=await page.locator('.modal').evaluate(el=>getComputedStyle(el).animationName);
if(animation!=='dialog-in')throw new Error('Missing modal entrance animation');
await page.screenshot({path:'test-results/project-detail-preview.png'});
await page.keyboard.press('Escape');
await page.locator('.is-closing').waitFor();
await page.getByRole('dialog').waitFor({state:'detached'});
await page.getByRole('button',{name:'All projects'}).click();
await page.setViewportSize({width:390,height:844});
await page.goto('http://localhost:5173');await page.getByRole('button',{name:'Enter portfolio'}).click();await page.locator('main').waitFor();
await page.getByRole('button',{name:'Toggle navigation'}).click();
await page.locator('nav').getByRole('link',{name:'About'}).click();
if(await page.locator('nav.open').count())throw new Error('Mobile nav did not close');
await page.screenshot({path:'test-results/mobile-preview.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
if(overflow)throw new Error('Mobile overflow');
await page.emulateMedia({reducedMotion:'reduce'});
await page.getByRole('button',{name:'View BASE project'}).click();
if(await page.locator('.modal').evaluate(el=>getComputedStyle(el).animationName)!=='none')throw new Error('Reduced motion failed');
await page.getByRole('button',{name:'Close project'}).click();
await page.getByRole('dialog').waitFor({state:'detached'});
if(await page.locator('.scene-background canvas').count()!==1)throw new Error('Missing 3D canvas');
if(errors.length)throw new Error(errors.join('\n'));
console.log('Passed: project filters, dialog/Escape, mobile navigation, mobile overflow, runtime errors.');
await browser.close();

