import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import Scene from './Scene';
import Welcome from './Welcome';
import Cursor from './Cursor';
import Typewriter from './Typewriter';
import {ArrowUpRight, ArrowDown, ArrowRight, Plus, Minus, Menu, X, Code2, Layers, Sparkles} from 'lucide-react';
import './style.css';

// Resume-backed profile. Add an email address to enable the contact link.
const profile = {name:'Simon Lee', role:'Senior Full Stack Engineer', email:''};
const projects = [
 {id:'01',name:'BASE',category:'E-commerce',type:'Web development',year:'01',style:'base',title:'An idea today.\nA business tomorrow.',subtitle:'Make your next big thing happen.',description:'Built scalable multi-tenant commerce functionality using React, Next.js, TypeScript, Node.js, PostgreSQL, Redis, and AWS. Improved API throughput by 40%, reduced initial page load time by 41%, and automated deployments from 60 minutes to under 15 minutes.',url:'https://thebase.com',tags:['Commerce','Responsive UI','Web experience']},
 {id:'02',name:'CureApp',category:'Healthcare',type:'Web development',year:'02',style:'cure',title:'Better care.\nBeyond the clinic.',subtitle:'A healthier future, connected.',description:'Built and maintained a digital therapeutics platform supporting 10K+ patient records. Improved response time by 32%, reduced manual workflows by 40%, and developed analytics pipelines processing 50K+ monthly events. Senior Software Engineer, March 2024 - present.',url:'https://cureapp.co.jp',tags:['Healthcare','Information design','Responsive UI']},
 {id:'03',name:'Kkoisland',category:'Bilingual web platform',type:'Interface design',year:'03',style:'keiko',title:'A little personality.\nA lot of possibility.',subtitle:'Frontend engineer & creative thinker.',description:'Built and maintained a bilingual Japanese/English publishing platform with desktop and feature-phone experiences. Organized historical newsletters into a durable web repository and preserved the legacy application on GitHub Pages. Web Developer, September 2014 - June 2017.',url:'https://www.kkoisland.com',tags:['Portfolio','Personal branding','Interface design']},
 {id:'04',name:'Mercari',category:'Marketplace',type:'Web development',year:'04',style:'mercari',title:'Find your next\nfavorite thing.',subtitle:'A marketplace full of possibilities.',description:'Built marketplace features with React, Next.js, TypeScript, Go, PostgreSQL, Redis, and AWS for 100K+ listings. Increased peak request throughput by 42%, improved search relevance by 31%, and cut deployment time from 75 minutes to under 15 minutes. Senior Full Stack Engineer, October 2020 - March 2024.',url:'https://www.mercari.com',tags:['Marketplace','Commerce','Product experience']},
];

function Preview({project:p}){
 return <div className={`preview ${p.style}`} aria-hidden="true"><div className="browser-bar"><span/><span/><span/><div>{p.name.toLowerCase().replace(' ','')}.com</div><Plus size={9}/></div><div className="mock-nav"><b>{p.style==='cure'?'✚ ':p.style==='mercari'?'▰ ':''}{p.name}</b><span>About &nbsp; Discover &nbsp; Contact</span><i>Explore ↗</i></div><div className="mock-body"><span className="mock-eyebrow">{p.subtitle}</span><h3>{p.title}</h3><span className="mock-button">{p.style==='cure'?'Discover our approach':'Explore more'} <ArrowRight size={11}/></span>{p.style==='base'?<div className="storefront"><div className="store-roof">✦ &nbsp; GOOD THINGS &nbsp; ✦</div><div className="store-window"><span>made<br/>for you.</span><div className="vase">✿</div></div><div className="store-floor"/></div>:p.style==='cure'?<div className="health-art"><div className="health-circle">✚</div><div className="health-label">♡ &nbsp; Everyday, a little better.<div className="pulse">⌁⌁⌁⌁⌁⌁⌁⌁</div></div></div>:p.style==='keiko'?<div className="sun-face">●‿●</div>:<div className="shopping-art"><div className="product-one">m<span>Something<br/>good awaits.</span></div><div className="product-two">✳<span>Find your favorite.</span></div></div>}</div><div className="mock-footer">{p.style==='base'?'YOUR IDEAS DESERVE A PLACE IN THE WORLD.':p.style==='cure'?'SCIENCE MEETS EVERYDAY LIFE.':p.style==='keiko'?'DESIGN. DEVELOP. REPEAT.':'A NEW LIFE FOR THE THINGS YOU LOVE.'}<ArrowUpRight size={12}/></div></div>
}
function App(){
 const [menu,setMenu]=useState(false),[filter,setFilter]=useState('All projects'),[selected,setSelected]=useState(null),[expanded,setExpanded]=useState(0),[copied,setCopied]=useState(false);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement;const key=e=>{if(e.key==='Escape')closeProject();if(e.key==='Tab'){const nodes=[...document.querySelectorAll('.modal button, .modal a')];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;previous?.focus();};},[selected]);
 const [closing,setClosing]=useState(false);
 const closeTimer=useRef(null);
 const closeProject=()=>{if(closeTimer.current)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setSelected(null);return;}setClosing(true);closeTimer.current=setTimeout(()=>{setSelected(null);setClosing(false);closeTimer.current=null;},260);};
 useEffect(()=>()=>clearTimeout(closeTimer.current),[]);
 const visible=projects.filter(p=>filter==='All projects'||p.type===filter);
 return <><Scene/><header><a className="logo" href="#home" aria-label="Simon Lee home">s<span>l</span><i>.</i></a><nav className={menu?'open':''}>{['Work','About','Expertise','Contact'].map(n=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setMenu(false)}>{n}{n==='Work'&&<sup>04</sup>}</a>)}</nav><a className="header-cta" href="#contact">Let’s talk <ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main><section className="hero" id="home"><div className="hero-content"><div className="eyebrow"><span className="status-dot"/> OPEN TO NEW OPPORTUNITIES</div><h1>Thoughtful code.<br/>Meaningful<br/><span>experiences.</span><span className="hero-asterisk">✳</span></h1><Typewriter/><p>I’m {profile.name}, a Senior Full Stack Engineer in Tokyo.<br className="desktop-br"/> 12+ years turning complex ideas into seamless digital experiences.</p><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowUpRight size={18}/></a><a className="text-button" href="#about">A little about me <ArrowRight size={16}/></a></div></div><div className="orb-caption"><span>01 / EXPLORING DIMENSIONS</span><span>CODE × CREATIVITY</span></div><div className="hero-bottom"><span>BASED IN TOKYO, JAPAN. &nbsp; BUILDING FOR EVERYWHERE.</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={13}/></a></div></section>
 <div className="stack-strip"><span>MY CREATIVE TOOLKIT</span><div><b className="react-icon">⚛</b> React</div><div><b className="ts-icon">TS</b> TypeScript</div><div><b>◈</b> Next.js</div><div><b>⬡</b> Node.js</div><div><b>〰</b> Tailwind CSS</div><div><b>△</b> Three.js</div></div>
 <section className="section work" id="work"><div className="section-kicker"><span>01 — SELECTED WORK</span><span>A FEW THINGS I’VE PUT MY HEART INTO</span></div><div className="section-heading"><h2>From idea to <em>impact.</em></h2><p>Scalable platforms. Real-world results.<br/>Built with purpose. Designed for people.</p></div><div className="filters">{['All projects','Web development','Interface design'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f}{f==='All projects'&&<span>04</span>}</button>)}</div><div className="project-grid">{visible.map(p=><button className="project-card" key={p.id} onClick={()=>setSelected(p)} aria-label={`View ${p.name} project`}><div className="project-visual"><Preview project={p}/><span className="project-open"><ArrowUpRight size={22}/></span></div><div className="project-info"><div><h3>{p.name}</h3><p>{p.category} <span>•</span> {p.type}</p></div><span className="project-number">/{p.id}</span></div></button>)}</div></section>
 <section className="section about" id="about"><div className="section-kicker"><span>02 — THE PERSON BEHIND THE PIXELS</span><Sparkles size={18}/></div><div className="about-grid"><h2>A curious mind.<br/>A builder’s <em>heart.</em></h2><div><p className="about-lead">I enjoy the space where thoughtful design meets thoughtful engineering.</p><p>Over 12+ years, I have built commerce platforms, healthcare products, and content-rich websites. My work spans React and TypeScript interfaces, Node.js and Go services, database design, and AWS infrastructure. I care about the entire experience, from an intuitive interface to a reliable deployment.</p><div className="about-tags"><span>Tokyo, Japan</span><span>12+ years of experience</span><span>Software Engineering  -  Tokyo Denki University</span></div></div></div></section>
 <section className="section experience"><div className="section-kicker"><span>A TRACK RECORD OF BUILDING</span><span>2014  -  PRESENT</span></div><div className="experience-list">{[{company:"CureApp",role:"Senior Software Engineer",date:"Mar 2024  -  Present",detail:"Digital therapeutics  -  10K+ patient records"},{company:"Mercari",role:"Senior Full Stack Engineer",date:"Oct 2020  -  Mar 2024",detail:"Marketplace engineering  -  100K+ product listings"},{company:"BASE",role:"Full Stack Engineer",date:"Oct 2017  -  Jul 2020",detail:"Multi-tenant commerce  -  41% faster page loads"},{company:"Kkoisland",role:"Web Developer",date:"Sep 2014  -  Jun 2017",detail:"Bilingual publishing  -  Desktop & mobile experiences"}].map(job=><div className="experience-row" key={job.company}><h3>{job.company}</h3><div><strong>{job.role}</strong><p>{job.detail}</p></div><span>{job.date}</span></div>)}</div></section><section className="section expertise" id="expertise"><div className="section-kicker"><span>03 — WHAT I BRING TO THE TABLE</span></div><div className="expertise-grid"><div><h2>Good design.<br/>Solid <em>foundations.</em></h2><p>Bringing every layer of a digital<br/>experience together.</p></div><div className="services">{[{name:'Frontend development',icon:Code2,text:'Responsive interfaces with React, thoughtfully structured components, and a focus on accessibility and performance.',tags:'React / TypeScript / Responsive design'},{name:'Backend & data systems',icon:Layers,text:'Scalable APIs, event-driven services, and efficient data systems powering commerce and healthcare products.',tags:'Node.js / Go / PostgreSQL / GraphQL / Redis'},{name:'Cloud & delivery',icon:Sparkles,text:'Reliable cloud infrastructure, automated testing, and CI/CD pipelines that turn complex releases into repeatable deployments.',tags:'AWS / Docker / Kubernetes / Terraform / GitHub Actions'}].map((s,i)=><div className={'service '+(expanded===i?'expanded':'')} key={s.name}><button id={`service-toggle-${i}`} aria-controls={`service-panel-${i}`} onClick={()=>setExpanded(expanded===i?-1:i)} aria-expanded={expanded===i}><s.icon size={20}/><span>{s.name}</span>{expanded===i?<Minus size={18}/>:<Plus size={18}/>}</button><div className="service-panel" id={`service-panel-${i}`} role="region" aria-labelledby={`service-toggle-${i}`} aria-hidden={expanded!==i}><div className="service-panel-inner"><div className="service-content"><p>{s.text}</p><small>{s.tags}</small></div></div></div></div>)}</div></div></section>
 <section className="contact section" id="contact"><div className="eyebrow"><span className="status-dot"/> GOOD THINGS START WITH A CONVERSATION</div><h2>Have something<br/>in <em>mind?</em> <span>↗</span></h2><div className="contact-bottom"><p>Let’s bring your next idea to life.<br/>I’d love to hear what you’re thinking.</p>{profile.email?<a className="button primary" href={`mailto:${profile.email}`}>Say hello <ArrowUpRight size={18}/></a>:<button className="button primary" onClick={()=>setCopied(true)}>Let’s connect <ArrowUpRight size={18}/></button>}</div>{copied&&<p className="contact-note" role="status">Contact details are coming soon. An email address was not included in the supplied resume.</p>}</section>
 </main><footer><a className="footer-name" href="#home">{profile.name}<span>{profile.role}</span></a><p>© {new Date().getFullYear()} · Crafted with care & a little curiosity.</p><a href="#home">Back to top <ArrowUpRight size={15}/></a></footer>
 {selected&&<div className={`modal-backdrop ${closing ? "is-closing" : ""}`} onClick={closeProject}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="project-title" onClick={e=>e.stopPropagation()}><button autoFocus className="modal-close" onClick={closeProject} aria-label="Close project"><X/></button><Preview project={selected}/><div className="modal-content"><span className="eyebrow">SELECTED WORK / {selected.category}</span><h2 id="project-title">{selected.name}</h2><p>{selected.description}</p><div className="about-tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><a className="button primary" href={selected.url} target="_blank" rel="noreferrer">Visit reference website <ArrowUpRight size={18}/></a><small>Visual preview recreated from the supplied project screenshot. Experience and results are drawn from the resume.</small></div></div></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<><Cursor/><Welcome><App/></Welcome></>);
